services:
  service-a:
    environment:
      OTEL_SDK_DISABLED: "true"

  service-b:
    environment:
      OTEL_SDK_DISABLED: "true"

  data-service:
    environment:
      OTEL_SDK_DISABLED: "true"
